# Generated by Django 5.0.1 on 2024-11-24 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemorder',
            unique_together=set(),
        ),
    ]
